quarkus.http.port=8181

quarkus.oidc.auth-server-url=http://localhost:8080/realms/test

quarkus.oidc.application-type=SERVICE

quarkus.oidc.client-id=actor-app

quarkus.oidc-client.auth-server-url=${quarkus.oidc.auth-server-url}
quarkus.oidc-client.client-id=${quarkus.oidc.client-id}
quarkus.oidc-client.credentials.secret=67KSG0c6tnOhJU2HSEP8OeuWXPyoGSiFvtX2x8xVMQ1wLswJFWCSZPkTIPezLQjtiwl6Ozb6IQt3mpS5eyqmDV
quarkus.oidc-client.grant.type=CLIENT

# Base URL of the Booking Service
subject-app/mp-rest/url=http://localhost:8180/
