quarkus.http.port=8180

quarkus.oidc.auth-server-url=http://localhost:8080/realms/test

quarkus.oidc.application-type=WEB_APP

quarkus.oidc.client-id=subject-app

quarkus.oidc.authentication.scopes=delegation:service-account-actor-app
